# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
      - mongodb_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  api:
    build: sae5.01-gestion_vacataires-API
    depends_on:
      - mongo
    ports:
      - 3000:3000
  angular:
    build: sae5.01-gestion_vacataires/s5.01-app-gestion-vacataires
    ports:
      - 80:4200


volumes:
  mongodb_volume: